services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ZooShopHelper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks: [backend]

  backend:
    build:
      context: ./ZooShopHelper
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/ZooShopHelper
    depends_on: [db]
    volumes:
      - ./ZooShopHelper/app:/api/app
    ports:
      - "8000:8000"
    networks: [backend]

  frontend:
    build:
      context: ./FrontEnd/projectshop
      dockerfile: Dockerfile
    environment:
      VUE_APP_API_URL: http://localhost:8000
    depends_on: [backend]
    volumes:
      - ./FrontEnd/projectshop:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks: [backend]

volumes:
  db_data:

networks:
  backend:
    driver: bridge
